### ISSUE TITLE
Mount certificate and private key for future updates

### ISSUE THREAD

**Issue by nomailme** [babagreensheep/jellyfin-tizen-docker#29]
Hi
Every time I try to update the app on the device I have to uninstall previous version of the app as the signature of the author certificate is chainging. 
I was wondering whether it is possible to mount a certificate and private key to host volume, so the certificate stays the same. I belive it will make it possible to update packages without uninstalling the previous version.

Thanks in advance,
@nomailme

**Comment by dgabka** [comment]
Nice idea, see #30

**Comment by nomailme** [comment]
Wow. That was fast :) Thank you!

**Comment by nomailme** [comment]
Maybe someone will find it useful. I have two Samsung TVs.
Below is the docker-compose.yml file I use to update them.
The folder structure is as follows:

```
jellyfin-client/
├─ docker-compose.yml <-- docker-compose.yml file that is listed below
├─ jellyfin-tizen-docker/ <-- clone of this repository

```

```
services:
  living-room:
    build:
      context: jellyfin-tizen-docker
      dockerfile: Dockerfile
      args:
        CERT_NAME: Jellyfin
        CERT_FILENAME: Jellyfin
        CERT_PASSWORD: 1234
        JELLYFIN_BRANCH: release-10.10.z
    environment:
      - TV_IP=192.168.4.12
    volumes:
      - ./jellyfin-tizen-docker/cert:/cert

  bedroom:
    build:
      context: jellyfin-tizen-docker
      dockerfile: Dockerfile
      args:
        CERT_NAME: Jellyfin
        CERT_FILENAME: Jellyfin
        CERT_PASSWORD: 1234
        JELLYFIN_BRANCH: release-10.10.z
    environment:
      - TV_IP=192.1684.13
    volumes:
      - ./jellyfin-tizen-docker/cert:/cert
```

Now the update for me is as simple as running ansible script that basically does `git pull, docker compose build and docker compose up`
